#!/bin/sh

#Load all new ZSH settings
source $HOME/.zshrc

if [ ! -e $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

echo "Installing VIM plugins..."
vim -u $HOME/.dotfiles/vimrc.bundles +PluginInstall +qa

cd $HOME/.dotfiles
brew tap Homebrew/bundle

echo "Installing brew formulas..."
brew bundle

echo "Installing pip..."
sudo easy_install pip

echo "Installing pip packages..."
source pipfile
