#!/bin/sh

# START - VIM PLUGINS #
if [ ! -e $HOME/.vim/bundle/vundle ]; then
  echo "Installing VIM plugins ..."
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim -u $HOME/.vimrc.bundles +PluginInstall +qa

cd $HOME/.dotfiles
brew bundle
# END - VIM PLUGINS #
